name: Desa Green
favicon: null
layout_spectrum: 0.09185
typography_spectrum: 0.27145
title: Desa Green @ Taman Desa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f3f8'
    - '#a2a6a5'
    - '#10150f'
    - '#556a7d'
    - '#324452'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3447656414937228
  rhythmicContrast: 0.5
purpose: []
